volumes:
  # 离线下载临时中转目录
  temp_data:
  # 配置卷 (可能不太行，得试一下)
  cloudreve:

services:
  cloudreve:
    container_name: cloudreve
    image: cloudreve/cloudreve:latest
    restart: unless-stopped
    ports:
      - "5212:5212"
    volumes:
      - temp_data:/data
      - cloudreve/uploads:/cloudreve/uploads
      - cloudreve/conf.ini:/cloudreve/conf.ini
      - cloudreve/cloudreve.db:/cloudreve/cloudreve.db
      - cloudreve/avatar:/cloudreve/avatar
    depends_on:
      - aria2

  aria2:
    container_name: aria2
    image: p3terx/aria2-pro
    restart: unless-stopped
    environment:
      - RPC_SECRET=MySecretJH3D7fn94P8XwidH4i
      - RPC_PORT=6800
    volumes:
      - cloudreve/aria2/config:/config
      - temp_data:/data

