volumes:
  mysql_data:
  nextcloud:
  apps:
  config:
  data:
  theme:

networks:
  nextcloud_network:
    driver: bridge

services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    ports:
      - "13306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlrootpassword
      - MYSQL_PASSWORD=mysqlpassword
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_LOG_BIN_EXPIRE_LOGS_DAYS=3
    networks:
      - nextcloud_network

  app:
    image: nextcloud:fpm
    restart: unless-stopped
    ports:
      - 18080:80
    depends_on:
      - db
    volumes:
      - nextcloud:/var/www/html
      - apps:/var/www/html/custom_apps
      - config:/var/www/html/config
      - data:/var/www/html/data
      - theme:/var/www/html/themes/my_themes
    environment:
      - MYSQL_PASSWORD=mysqlpassword
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - NEXTCLOUD_ADMIN_USER=root
      - NEXTCLOUD_ADMIN_PASSWORD=rootpassword
      - NEXTCLOUD_TRUSTED_DOMAINS=*
    networks:
      - nextcloud_network

  web:
    image: nginx
    restart: unless-stopped
    ports:
      - 18080:80
      - 11443:443
    depends_on:
      - app
    volumes_from:
      - app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/cert.crt:/etc/nginx/certs/cert.crt
      - ./nginx/cert.key:/etc/nginx/certs/cert.key
    