services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - "9443:9443"   # https
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /docker/portainer_data:/data

    