services:
  nginx:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    network_mode: "host"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - /ssl:/ssl
    
