volumes:
  mysql_data:

services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MY_TEST_ENV: "value with spaces"
    ports:
      - "53306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

